echo "[Running covid reports]"
python3 covid.py graph1 --states "USA"  "New York" --vars "casesc"  "deathsc"
python3 covid.py graph2 --states "USA"  "New York" --vars "casesr"  "deathsr"
python3 covid.py graph3 --states "Massachusetts" "Florida" "California"  "Washington" --vars "casesc"  "deathsc"
python3 covid.py graph4 --states "Massachusetts" "Florida" "California"  "Washington" --vars "casesr"  "deathsr"
python3 covid.py graph5 --states "Massachusetts" "Florida" "California"  "Washington" --vars "casesd"  "deathsd"
